name: Security Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  precogs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: PrecogsAI/precogs-action@v1
